version: "3"

services:
    test:
        image: "token_auth_server"
        container_name: "test"
        working_dir: /token_auth_server
        environment:
            - PYTHONPATH=/
        volumes:
            - .:/token_auth_server
        command: ["pytest"]
