version: "3"

services:
    token_test:
        image: "token_auth_server"
        container_name: "token_auth_server"
        working_dir: /token_test
        volumes:
            - .:/token_test
        command: ["python", "token.py"]
